openapi: 3.0.0
info:
  title: API Sintergica
  description: API para gestionar clientes, empresas y roles
  version: 1.0.0

paths:
  /clients:
    get:
      summary: Obtener todos los clientes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de clientes obtenida correctamente
    post:
      summary: Registrar un nuevo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Cliente registrado exitosamente
        '400':
          description: El cliente ya existe

  /clients/login:
    post:
      summary: Iniciar sesión de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Inicio de sesión exitoso
        '400':
          description: Credenciales incorrectas

  /clients/addClientToCompany:
    post:
      summary: Agregar un cliente a una empresa
      security:
        - bearerAuth: []
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
        - name: targetCompany
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cliente agregado a la empresa
        '400':
          description: Error en los datos proporcionados

  /clients/changeRolClient:
    post:
      summary: Cambiar el rol de un cliente
      security:
        - bearerAuth: []
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
        - name: newRolUser
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Rol cambiado correctamente
        '400':
          description: Error en los datos proporcionados

  /company:
    get:
      summary: Obtener todas las compañías
      responses:
        '200':
          description: Lista de compañías obtenida correctamente
    post:
      summary: Agregar una nueva compañía
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: Compañía agregada correctamente

  /company/getCompany:
    post:
      summary: Obtener una compañía por UUID
      parameters:
        - name: uuid
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Compañía encontrada correctamente
        '404':
          description: Compañía no encontrada

  /group:
    get:
      summary: Obtener todos los grupos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de grupos obtenida correctamente
    post:
      summary: Agregar un nuevo grupo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: Grupo agregado correctamente

  /group/addNewClientToGroup:
    get:
      summary: Agregar un cliente a un grupo
      security:
        - bearerAuth: []
      parameters:
        - name: groupId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: emailUser
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cliente agregado al grupo correctamente
        '400':
          description: Error en los datos proporcionados

  /group/getGroupByUUID:
    get:
      summary: Obtener un grupo por UUID
      parameters:
        - name: groupUUID
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Grupo encontrado correctamente
        '404':
          description: Grupo no encontrado

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        rol:
          type: string
        company:
          type: string
          nullable: true
    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    Company:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    Group:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        company:
          type: string
          format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
