spring:
  application:
    name: APIV2

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20 # Máximo de conexiones concurrentes
      connection-timeout: 5000 # 5 segundos (ajusta según latencia)
      idle-timeout: 300000 # 5 minutos
      max-lifetime: 240000 # 4 minutos
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30 # Optimiza inserts/updates
          fetch_size: 100 # Reduce viajes a la BD
        default_batch_fetch_size: 20 # Evita N+1 en relaciones

  config:
    import:
      - "messages.yml"
  mail:
    server: mail.sintergica.ai
    enable-auth: true
    enable-tls: true
    smtp-port: 465
    ssl-port: 465
    from-email: turing@sintergica.ai
    email-password: ${EMAIL_PASSWORD}
    base-url: http://localhost:8080

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

michelle:
  url: "https://michelle-hoyto.ondigitalocean.app/event"
  token: ${DATASOURCE_PASSWORD}

server:
  port: 8080
