name: "🐋Build Docker image"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      deploy:
        type: boolean
        description: Desplegar en dev
        required: true
        default: false
      iport:
        type: number
        description: Puerto interno del servicio
        required: true
      eport:
        type: number
        description: Puerto externo del servicio
        required: true

env:
  IMAGE_NAME: ghcr.io/sintergicaai/turing-admin

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: corretto
          java-version: 17

      - name: Login on DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: GTWALOM
          password: ${{ secrets.ANTON_TOKEN }}

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure buildx
        uses: docker/setup-buildx-action@v1.0.0

      - name: Clean
        run: mvn clean

      - name: Compile
        run: mvn compile

      - name: Package
        run: mvn package

      - name: Start buildx
        uses: docker/build-push-action@v4.0.0
        id: build
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ inputs.tag }},${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          push: true

  deploy:
    needs: build_image
    if: ${{ inputs.deploy }}
    uses: ./.github/workflows/deploy_dev.yaml
    with:
      eport: ${{ fromJSON(inputs.eport) }}
      iport: ${{ fromJSON(inputs.iport) }}
      tag: ${{ inputs.tag }}
    secrets: inherit
