name: "Deploy on dev"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      iport:
        type: number
        description: Puerto interno del servicio
        required: true
      eport:
        type: number
        description: Puerto externo del servicio
        required: true

env:
  FULL_IMAGE_TAG: ghcr.io/sintergicaai/turing-admin${{ inputs.tag }}

jobs:
  pull_image:
    runs-on: [ self.hosted, awsdev ]
    steps:
      - name: Pull image
        run: pull ${{ env.FULL_IMAGE_TAG }}

      - name: Run container
        run: docker run -d -p ${{ inputs.eport }}:${{ inputs.iport }} --env-file /home/admin/.env ${{ env.FULL_IMAGE_TAG }}
